# Generated by Django 3.0.6 on 2020-06-29 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables_daniel', '0002_auto_20200629_1254'),
    ]

    atomic = False

    operations = [
        migrations.RenameModel(
            old_name='CompanyTable',
            new_name='Companies',
        ),
        migrations.RenameModel(
            old_name='GlassdoorTable',
            new_name='Reviews',
        ),
    ]
