# Generated by Django 3.0.6 on 2020-07-02 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables_daniel', '0005_auto_20200629_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='CompanyID',
        ),
        migrations.AlterField(
            model_name='company',
            name='Company',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='Company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables_daniel.Company'),
        ),
    ]
